/*
characterAttributes['模板'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 
};
*/
characterAttributes['偶像伊娃'] = {
    roleProperties: '虚',      
    roleOccupation: '辅助',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 6,            
    addAtk: 58,          
    addDef: 38,          
    addHP: 48,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 123,        
    basicDef: 12,        
    basicHP: 1234,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 0,

};
characterAttributes['兰儿∧手套'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 53,          
    addDef: 45,          
    addHP: 35,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 123,        
    basicDef: 29,        
    basicHP: 1000,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 

};
characterAttributes['兰儿∧篮子'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 53,          
    addDef: 45,          
    addHP: 35,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 123,        
    basicDef: 29,        
    basicHP: 1000,      
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 

};
characterAttributes['奈莉'] = {
    roleProperties: '虚',      
    roleOccupation: '射手',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 59,          
    addDef: 45.5,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 135,        
    basicDef: 23,        
    basicHP: 986,         
    basicHeal: 0,       
    skill: 18,           
    cdSkill: 0, 

};
characterAttributes['未来骑士∧单手剑'] = {
    roleProperties: '虚',       
    roleOccupation: '战士',     
    weaponType: '单手剑',      
    weapon2Type: '盾牌',
    crit: 5,                    
    addAtk: 61,                  
    addDef: 41,                  
    addHP: 36,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 128,                
    basicDef: 24,                
    basicHP: 1080,                 
    basicHeal: 0,                
    skill: 10,                  
    cdSkill: 0,

};
characterAttributes['未来骑士∧双手剑'] = {
    roleProperties: '虚',       
    roleOccupation: '战士',     
    weaponType: '双手剑',      
    weapon2Type: '无',
    crit: 5,                    
    addAtk: 61,                  
    addDef: 41,                  
    addHP: 36,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 128,                
    basicDef: 24,                
    basicHP: 1080,                 
    basicHeal: 0,                
    skill: 10,                  
    cdSkill: 0,
    
};
characterAttributes['未来骑士∧步枪'] = {
    roleProperties: '虚',       
    roleOccupation: '战士',     
    weaponType: '步枪',      
    weapon2Type: '无',
    crit: 5,                    
    addAtk: 61,                  
    addDef: 41,                  
    addHP: 36,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 128,                
    basicDef: 24,                
    basicHP: 1080,                 
    basicHeal: 0,                
    skill: 10,                  
    cdSkill: 0,
    
};
characterAttributes['未来骑士∧弓'] = {
    roleProperties: '虚',       
    roleOccupation: '战士',     
    weaponType: '弓',      
    weapon2Type: '无',
    crit: 5,                    
    addAtk: 61,                  
    addDef: 41,                  
    addHP: 36,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 128,                
    basicDef: 24,                
    basicHP: 1080,                 
    basicHeal: 0,                
    skill: 10,                  
    cdSkill: 0,
   
};
characterAttributes['索菲∧泳装'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 56,          
    addDef: 39,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 120,        
    basicDef: 34,        
    basicHP: 999,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 4,
 
};
characterAttributes['埃里娜'] = {
    roleProperties: '虚',      
    roleOccupation: '坦克',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 0,            
    addAtk: 47,          
    addDef: 43,          
    addHP: 44,           
    addHeal: 0,         
    reduceDamage: 21,    
    basicAtk: 114,        
    basicDef: 28,        
    basicHP: 1040,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 2,
 
};
characterAttributes['康娜'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 54,          
    addDef: 42,          
    addHP: 39,           
    addHeal: 0,         
    reduceDamage: 14,    
    basicAtk: 151,        
    basicDef: 35,        
    basicHP: 1078,         
    basicHeal: 0,       
    skill: 8,           
    cdSkill: 0,
 
};
characterAttributes['罗兰茵∧泳装'] = {
    roleProperties: '虚',      
    roleOccupation: '射手',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 61,          
    addDef: 39,          
    addHP: 44,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 150,        
    basicDef: 40,        
    basicHP: 1045,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 0,
 
};
characterAttributes['克罗姆小姐'] = {
    roleProperties: '虚',       
    roleOccupation: '射手',     
    weaponType: '步枪',      
    weapon2Type: '步枪',
    crit: 0,                    
    addAtk: 68,                  
    addDef: 39,                  
    addHP: 43,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 100,                
    basicDef: 40,                
    basicHP: 750,                 
    basicHeal: 0,                
    skill: 10,                  
    cdSkill: 6 ,
 
};
characterAttributes['银河'] = {
    roleProperties: '虚',       /* 角色属性 */
    roleOccupation: '射手',     /* 角色职业 */
    weaponType: '篮子',       /* 主武器类型 */
    weapon2Type: '无',          /* 副武器类型 */
    crit: 4,                    /* 满破自带暴击 */
    addAtk: 64,                  /* 满破攻击觉醒 */
    addDef: 42,                  /* 满破防御觉醒 */
    addHP: 43,                   /* 满破生命觉醒 */
    addHeal: 0,                 /* 满破回血觉醒 */
    reduceDamage: 0,            /* 伤害减免 */
    basicAtk: 151,                /* 1级攻击白值 */
    basicDef: 41,                /* 1级防御白值 */
    basicHP: 1102,                 /* 1级生命白值 */
    basicHeal: 1250,               /* 五星回血值白值 */
    skill: 0,                   /* 满破总技伤 */
    cdSkill: 0,                  /* 角色自带cd */

};
characterAttributes['米可'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 66,          
    addDef: 40,          
    addHP: 39,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 136,        
    basicDef: 36,        
    basicHP: 1265,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 3 ,
     
};
// characterAttributes['？？？']
// characterAttributes['？？？']
characterAttributes['达伊'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 61,          
    addDef: 40,          
    addHP: 42,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 126,        
    basicDef: 50,        
    basicHP: 1150,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 4,
 
};
characterAttributes['骑士∧单手剑∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 3,            
    addAtk: 55,          
    addDef: 41,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 110,        
    basicDef: 20,        
    basicHP: 1000,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 5, 
};
characterAttributes['骑士∧双手剑∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 55,          
    addDef: 41,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 110,        
    basicDef: 20,        
    basicHP: 1000,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 5   
};
characterAttributes['骑士∧步枪∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 55,          
    addDef: 41,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 110,        
    basicDef: 20,        
    basicHP: 1000,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 5       
};
characterAttributes['骑士∧弓∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '弓',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 55,          
    addDef: 41,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 110,        
    basicDef: 20,        
    basicHP: 1000,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 5    
};
characterAttributes['罗兰茵∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '辅助',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 2,            
    addAtk: 42,          
    addDef: 37,          
    addHP: 44,           
    addHeal: 24,         
    reduceDamage: 0,    
    basicAtk: 108,        
    basicDef: 24,        
    basicHP: 1008,         
    basicHeal: 1478,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['岚芳∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '坦克',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 38,          
    addDef: 48,          
    addHP: 55,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 96,        
    basicDef: 38,        
    basicHP: 1050,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['艾米∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 69,          
    addDef: 32.5,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 113,        
    basicDef: 26,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['莉耶∧二星'] = {
    roleProperties: '虚',      
    roleOccupation: '射手',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 13,            
    addAtk: 62,          
    addDef: 38.5,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 122,        
    basicDef: 20,        
    basicHP: 900,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 0, 
};
