/*
characterAttributes['模板'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['芭莉∧篮子'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+单手剑+盾'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+双手剑'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+步枪+步枪'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '步枪',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+权杖'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+弓'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '弓',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+手套'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['芭莉+爪'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 62,          
    addDef: 37,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 160,        
    basicDef: 30,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['蒂尼亚'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '弓',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 64,          
    addDef: 41,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 118,        
    basicDef: 27,        
    basicHP: 985,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 0          
};
characterAttributes['阿勒夫'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 53,          
    addDef: 40,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 10,    
    basicAtk: 120,        
    basicDef: 37,        
    basicHP: 1090,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 6          
};
characterAttributes['鲁∧步枪'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 57,          
    addDef: 39,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 133,        
    basicDef: 60,        
    basicHP: 1030,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 4          
};
characterAttributes['鲁∧双手剑'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 57,          
    addDef: 39,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 133,        
    basicDef: 60,        
    basicHP: 1030,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 4          
};
characterAttributes['梅丽尔'] = {
    roleProperties: '土',      
    roleOccupation: '辅助',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 61,          
    addDef: 36,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 22,    
    basicAtk: 125,        
    basicDef: 32,        
    basicHP: 1000,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0          
};
characterAttributes['卡麦尔'] = {
    roleProperties: '土',      
    roleOccupation: '辅助',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 58,          
    addDef: 35,          
    addHP: 39,           
    addHeal: 0,         
    reduceDamage: 16,    
    basicAtk: 129,        
    basicDef: 44,        
    basicHP: 1020,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 4          
};
characterAttributes['帕尔瓦蒂'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 62,          
    addDef: 38,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 116,        
    basicDef: 30,        
    basicHP: 979,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 6          
};
characterAttributes['疯狂熊猫团'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 67,          
    addDef: 40,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 110,        
    basicDef: 40,        
    basicHP: 900,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 4          
};
characterAttributes['罗塞塔'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 41,          
    addHP: 42,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 150,        
    basicDef: 36,        
    basicHP: 980,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 0          
};
characterAttributes['爱梅莉丝'] = {
    roleProperties: '土',      
    roleOccupation: '射手',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 64,          
    addDef: 40,          
    addHP: 43,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 124,        
    basicDef: 20,        
    basicHP: 880,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 0          
};
characterAttributes['莫莉安'] = {
    roleProperties: '土',      
    roleOccupation: '坦克',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 0,            
    addAtk: 60,          
    addDef: 41,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 110,        
    basicDef: 27,        
    basicHP: 1114,         
    basicHeal: 0,       
    skill: 12,           
    cdSkill: 8          
};
// characterAttributes['？？？']
// characterAttributes['？？？']
characterAttributes['玛姆'] = {
    roleProperties: '土',      
    roleOccupation: '辅助',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 57,          
    addDef: 45,          
    addHP: 46,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 107,        
    basicDef: 24,        
    basicHP: 1071,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 0          
};
/*
characterAttributes['青叶'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['赫卡忒'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['玛丽安'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['马修'] = {
    roleProperties: '土',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['克雷格∧二星'] = {
    roleProperties: '土',      
    roleOccupation: '坦克',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 3,            
    addAtk: 38,          
    addDef: 44,          
    addHP: 58,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 87,        
    basicDef: 36,        
    basicHP: 1070,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 0          
};
characterAttributes['克雷格∧三星'] = {
    roleProperties: '土',      
    roleOccupation: '坦克',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 3,            
    addAtk: 44,          
    addDef: 46,          
    addHP: 60,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 102,        
    basicDef: 39,        
    basicHP: 1177,         
    basicHeal: 0,       
    skill: 3,           
    cdSkill: 0           
};