/*
characterAttributes['模板'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 
};
*/
characterAttributes['普利特维采∧双手剑'] = {
    roleProperties: '火',       
    roleOccupation: '战士',     
    weaponType: '双手剑',      
    weapon2Type: '无',
    crit: 3,                    
    addAtk: 67,                  
    addDef: 39,                  
    addHP: 39,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 116,                
    basicDef: 32,                
    basicHP: 1071,                 
    basicHeal: 0,                
    skill: 15,                  
    cdSkill: 0, 
};
characterAttributes['普利特维采∧单手剑'] = {
    roleProperties: '火',       
    roleOccupation: '战士',     
    weaponType: '单手剑',      
    weapon2Type: '无',
    crit: 3,                    
    addAtk: 67,                  
    addDef: 39,                  
    addHP: 39,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 116,                
    basicDef: 32,                
    basicHP: 1071,                 
    basicHeal: 0,                
    skill: 15,                  
    cdSkill: 0, 
};
characterAttributes['比什巴赫∧爪'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 56,          
    addDef: 45,          
    addHP: 46,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 117,        
    basicDef: 32,        
    basicHP: 1040,         
    basicHeal: 0,       
    skill: 9,           
    cdSkill: 0, 
};
characterAttributes['比什巴赫∧手套'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 56,          
    addDef: 45,          
    addHP: 46,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 117,        
    basicDef: 32,        
    basicHP: 1040,         
    basicHeal: 0,       
    skill: 9,           
    cdSkill: 0, 
};
characterAttributes['美娅'] = {
    roleProperties: '火',      
    roleOccupation: '辅助',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 52,          
    addDef: 38,          
    addHP: 42,           
    addHeal: 23,         
    reduceDamage: 0,    
    basicAtk: 129,        
    basicDef: 34,        
    basicHP: 980,         
    basicHeal: 1562,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['琳'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 62,          
    addDef: 41,          
    addHP: 43,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 137,        
    basicDef: 56,        
    basicHP: 1045,         
    basicHeal: 0,       
    skill: 18,           
    cdSkill: 0, 
};
characterAttributes['罗茜'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 37,          
    addHP: 44,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 132,        
    basicDef: 39,        
    basicHP: 960,         
    basicHeal: 0,       
    skill: 11,           
    cdSkill: 0, 
};
characterAttributes['辛缇拉'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 57,          
    addDef: 37.5,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 20,    
    basicAtk: 126,        
    basicDef: 15,        
    basicHP: 1120,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0, 
};
characterAttributes['克拉拉'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '弓',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 67,          
    addDef: 39,          
    addHP: 36,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 141,        
    basicDef: 34,        
    basicHP: 931,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0, 
};
characterAttributes['蕾伊'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 63,          
    addDef: 40,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 144,        
    basicDef: 44,        
    basicHP: 1143,         
    basicHeal: 0,       
    skill: 13,           
    cdSkill: 0, 
};
characterAttributes['拜蒙'] = {
    roleProperties: '火',      
    roleOccupation: '坦克',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 53,          
    addDef: 44,          
    addHP: 49,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 108,        
    basicDef: 28,        
    basicHP: 1133,         
    basicHeal: 0,       
    skill: 8,           
    cdSkill: 0, 
};
characterAttributes['艾米∧泳装'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 64,          
    addDef: 43,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 137,        
    basicDef: 46,        
    basicHP: 1110,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 4, 
};
characterAttributes['云苓'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 40,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 130,        
    basicDef: 16,        
    basicHP: 976,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 6, 
};
// characterAttributes['？？？']
// characterAttributes['？？？']
characterAttributes['莉娜'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 59,          
    addDef: 36,          
    addHP: 39,           
    addHeal: 0,         
    reduceDamage: 20,    
    basicAtk: 130,        
    basicDef: 22,        
    basicHP: 883,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 4, 
};
characterAttributes['波普'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 63,          
    addDef: 42,          
    addHP: 44,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 143,        
    basicDef: 28,        
    basicHP: 1036,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 0, 
};
characterAttributes['朱菜'] = {
    roleProperties: '火',      
    roleOccupation: '辅助',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 52,          
    addDef: 40,          
    addHP: 41,           
    addHeal: 20,         
    reduceDamage: 0,    
    basicAtk: 125,        
    basicDef: 30,        
    basicHP: 1018,         
    basicHeal: 1530,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['埃尔韦拉∧二星'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 2,            
    addAtk: 69,          
    addDef: 35.6,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 125,        
    basicDef: 21,        
    basicHP: 984,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['埃尔韦拉∧三星'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 12,            
    addAtk: 73,          
    addDef: 38.6,          
    addHP: 43,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 135,        
    basicDef: 21,        
    basicHP: 1083,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0, 
};
characterAttributes['拉比∧二星'] = {
    roleProperties: '火',      
    roleOccupation: '坦克',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 38,          
    addDef: 49,          
    addHP: 51,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 98,        
    basicDef: 36,        
    basicHP: 1060,         
    basicHeal: 0,       
    skill: 2,           
    cdSkill: 4, 
};
characterAttributes['赤雪∧二星'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 16,            
    addAtk: 56,          
    addDef: 36,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 138,        
    basicDef: 42,        
    basicHP: 980,         
    basicHeal: 0,       
    skill: 5,           
    cdSkill: 0, 
};
characterAttributes['道尔夫∧二星'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 90,          
    addDef: 30,          
    addHP: 35,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 122,        
    basicDef: 18,        
    basicHP: 979,         
    basicHeal: 0,       
    skill: 14,           
    cdSkill: 0, 
};
characterAttributes['吉尔瓦斯∧二星'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 60,          
    addDef: 41,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 118,        
    basicDef: 22,        
    basicHP: 950,         
    basicHeal: 0,       
    skill: 14,           
    cdSkill: 0, 
};
