/*
characterAttributes['模板'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['普利特维采∧双手剑'] = {
    roleProperties: '火',       
    roleOccupation: '战士',     
    weaponType: '双手剑',      
    weapon2Type: '无',
    crit: 3,                    
    addAtk: 67,                  
    addDef: 39,                  
    addHP: 39,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 116,                
    basicDef: 32,                
    basicHP: 1071,                 
    basicHeal: 0,                
    skill: 15,                  
    cdSkill: 0          
};
characterAttributes['普利特维采∧单手剑'] = {
    roleProperties: '火',       
    roleOccupation: '战士',     
    weaponType: '单手剑',      
    weapon2Type: '无',
    crit: 3,                    
    addAtk: 67,                  
    addDef: 39,                  
    addHP: 39,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 116,                
    basicDef: 32,                
    basicHP: 1071,                 
    basicHeal: 0,                
    skill: 15,                  
    cdSkill: 0          
};
characterAttributes['比什巴赫∧爪'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['比什巴赫∧手套'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['美娅'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['琳'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['罗茜'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['辛缇拉'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['克拉拉'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['蕾伊'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['拜蒙'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['艾米∧泳装'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['云苓'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 40,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 6          
};
// characterAttributes['？？？']
// characterAttributes['？？？']
characterAttributes['莉娜'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['波普'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['埃尔韦拉∧二星'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 2,            
    addAtk: 67,          
    addDef: 35.6,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 125,        
    basicDef: 21,        
    basicHP: 984,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['埃尔韦拉∧三星'] = {
    roleProperties: '火',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 12,            
    addAtk: 77,          
    addDef: 38.6,          
    addHP: 43,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 135,        
    basicDef: 21,        
    basicHP: 1083,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
/*
characterAttributes['拉比'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['赤雪'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
/*
characterAttributes['道尔夫'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['吉尔瓦斯'] = {
    roleProperties: '火',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/