/*
characterAttributes['模板'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['拉碧丝∧单手剑'] = {
    roleProperties: '光',       
    roleOccupation: '战士',     
    weaponType: '单手剑',      
    weapon2Type: '盾牌',
    crit: 8,                    
    addAtk: 58,                  
    addDef: 41,                  
    addHP: 42,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 116,                
    basicDef: 24,                
    basicHP: 1081,                 
    basicHeal: 0,                
    skill: 0,                  
    cdSkill: 6         
};
characterAttributes['拉碧丝∧双手剑'] = {
    roleProperties: '光',       
    roleOccupation: '战士',     
    weaponType: '双手剑',      
    weapon2Type: '无',
    crit: 8,                    
    addAtk: 58,                  
    addDef: 41,                  
    addHP: 42,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 116,                
    basicDef: 24,                
    basicHP: 1081,                 
    basicHeal: 0,                
    skill: 0,                  
    cdSkill: 6         
};
characterAttributes['尤金'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 2,            
    addAtk: 63,          
    addDef: 38,          
    addHP: 35,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 114,        
    basicDef: 37,        
    basicHP: 1061,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 6          
};
characterAttributes['未来公主'] = {
    roleProperties: '光',      
    roleOccupation: '坦克',    
    weaponType: '权杖',      
    weapon2Type: '盾牌',  
    crit: 0,            
    addAtk: 48,          
    addDef: 47,          
    addHP: 49,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 118,        
    basicDef: 26,        
    basicHP: 1030,         
    basicHeal: 0,       
    skill: 17,           
    cdSkill: 0          
};
characterAttributes['加百列'] = {
    roleProperties: '光',      
    roleOccupation: '辅助',    
    weaponType: '弓',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 64,          
    addDef: 40,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 120,        
    basicDef: 30,        
    basicHP: 937,         
    basicHeal: 1698,       
    skill: 10,           
    cdSkill: 4          
};
characterAttributes['MK.99'] = {
    roleProperties: '光',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 68,          
    addDef: 36,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 130,        
    basicDef: 27,        
    basicHP: 1010,         
    basicHeal: 0,       
    skill: 16,           
    cdSkill: 4          
};
characterAttributes['埃莉诺'] = {
    roleProperties: '光',      
    roleOccupation: '辅助',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 39,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 124,        
    basicDef: 30,        
    basicHP: 1121,         
    basicHeal: 1658,       
    skill: 10,           
    cdSkill: 2          
};
characterAttributes['卡洛儿'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 69,          
    addDef: 37,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 137,        
    basicDef: 60,        
    basicHP: 1082,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 7          
};
characterAttributes['普利希拉'] = {
    roleProperties: '光',      
    roleOccupation: '射手',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 69,          
    addDef: 33,          
    addHP: 36,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 124,        
    basicDef: 48,        
    basicHP: 1100,         
    basicHeal: 0,       
    skill: 12,           
    cdSkill: 4          
};
characterAttributes['瓦伦西亚'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 72,          
    addDef: 37,          
    addHP: 39,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 138,        
    basicDef: 60,        
    basicHP: 1070,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 0          
};
characterAttributes['凯伊'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 63,          
    addDef: 42,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 140,        
    basicDef: 40,        
    basicHP: 1170,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 2          
};
characterAttributes['千虑'] = {
    roleProperties: '光',      
    roleOccupation: '射手',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 64,          
    addDef: 42,          
    addHP: 43,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 138,        
    basicDef: 24,        
    basicHP: 1220,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['夏皮拉∧泳装'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 64,          
    addDef: 42,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 113,        
    basicDef: 32,        
    basicHP: 1080,         
    basicHeal: 0,       
    skill: 8,           
    cdSkill: 6          
};
characterAttributes['奥迪尔'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 64,          
    addDef: 40,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 134,        
    basicDef: 34,        
    basicHP: 970,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 7          
};
// characterAttributes['？？？']
// characterAttributes['？？？']
characterAttributes['高里'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 56,          
    addDef: 38.2,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 33,    
    basicAtk: 115,        
    basicDef: 36,        
    basicHP: 1018,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['伊娃∧二星'] = {
    roleProperties: '光',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 80,          
    addDef: 34,          
    addHP: 39,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 111,        
    basicDef: 36,        
    basicHP: 940,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['索菲∧二星'] = {
    roleProperties: '光',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 29.5,          
    addHP: 44,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 113,        
    basicDef: 32,        
    basicHP: 1030,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 0          
};
characterAttributes['梅儿佩儿∧二星'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 67,          
    addDef: 42,          
    addHP: 40,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 105,        
    basicDef: 30,        
    basicHP: 1003,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['梅儿佩儿∧三星'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 3,            
    addAtk: 71,          
    addDef: 45,          
    addHP: 43,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 107,        
    basicDef: 30,        
    basicHP: 1124,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['阿依莎∧二星'] = {
    roleProperties: '光',      
    roleOccupation: '辅助',    
    weaponType: '单手剑',      
    weapon2Type: '盾牌',  
    crit: 4,            
    addAtk: 40,          
    addDef: 47,          
    addHP: 52,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 93,        
    basicDef: 22,        
    basicHP: 930,         
    basicHeal: 0,       
    skill: 6,           
    cdSkill: 0          
};
characterAttributes['奈娃∧二星'] = {
    roleProperties: '光',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 67,          
    addDef: 37,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 104,        
    basicDef: 30,        
    basicHP: 988,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
