/*
characterAttributes['模板'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['玛丽娜'] = {
    roleProperties: '水',       
    roleOccupation: '坦克',     
    weaponType: '单手剑',      
    weapon2Type: '无',
    crit: 0,                    
    addAtk: 45,                  
    addDef: 41,                  
    addHP: 57,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 124,                
    basicDef: 76,                
    basicHP: 1080,                 
    basicHeal: 0,                
    skill: 4,                  
    cdSkill: 8       
};
characterAttributes['比安卡'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 2,            
    addAtk: 53,          
    addDef: 45,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 116,        
    basicDef: 24,        
    basicHP: 1020,         
    basicHeal: 0,       
    skill: 14,           
    cdSkill: 0          
};
characterAttributes['佳岚∧弓'] = {
    roleProperties: '水',       
    roleOccupation: '射手',     
    weaponType: '弓',      
    weapon2Type: '无',
    crit: 0,                    
    addAtk: 63,                  
    addDef: 41,                  
    addHP: 42,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 153,                
    basicDef: 16,                
    basicHP: 961,                 
    basicHeal: 1512,                
    skill: 6,                  
    cdSkill: 8  
};
characterAttributes['佳岚∧篮子'] = {
    roleProperties: '水',       
    roleOccupation: '射手',     
    weaponType: '篮子',      
    weapon2Type: '无',
    crit: 0,                    
    addAtk: 63,                  
    addDef: 41,                  
    addHP: 42,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 153,                
    basicDef: 16,                
    basicHP: 961,                 
    basicHeal: 1512,                
    skill: 6,                  
    cdSkill: 8  
};
characterAttributes['维罗妮卡'] = {
    roleProperties: '水',      
    roleOccupation: '辅助',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 58,          
    addDef: 43,          
    addHP: 44,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 128,        
    basicDef: 48,        
    basicHP: 920,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0          
};
characterAttributes['柚子∧泳装'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '双手剑',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 55,          
    addDef: 38,          
    addHP: 42,           
    addHeal: 0,         
    reduceDamage: 16,    
    basicAtk: 117,        
    basicDef: 29,        
    basicHP: 1050,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 6          
};
characterAttributes['奥尔卡'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 61,          
    addDef: 34,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 11,    
    basicAtk: 148,        
    basicDef: 31,        
    basicHP: 1006,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0          
};
characterAttributes['哈娜'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 59,          
    addDef: 39,          
    addHP: 37,           
    addHeal: 0,         
    reduceDamage: 13,    
    basicAtk: 59,        
    basicDef: 39,        
    basicHP: 37,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0          
};
characterAttributes['娅拉'] = {
    roleProperties: '水',      
    roleOccupation: '辅助',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 66,          
    addDef: 34,          
    addHP: 35,           
    addHeal: 0,         
    reduceDamage: 12,    
    basicAtk: 132,        
    basicDef: 37,        
    basicHP: 1020,         
    basicHeal: 0,       
    skill: 8,           
    cdSkill: 4          
};
characterAttributes['AA72'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 4,            
    addAtk: 59,          
    addDef: 34,          
    addHP: 42,           
    addHeal: 0,         
    reduceDamage: 12,    
    basicAtk: 148,        
    basicDef: 36,        
    basicHP: 987,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['安德拉斯'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 2,            
    addAtk: 71,          
    addDef: 40.5,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 152,        
    basicDef: 24,        
    basicHP: 1100,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 6          
};
characterAttributes['白雪'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '手套',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 66,          
    addDef: 41,          
    addHP: 38,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 118,        
    basicDef: 36,        
    basicHP: 965,         
    basicHeal: 0,       
    skill: 8,           
    cdSkill: 0          
};
characterAttributes['汐雅'] = {
    roleProperties: '水',      
    roleOccupation: '辅助',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 52,          
    addDef: 40.4,          
    addHP: 42,           
    addHeal: 23,         
    reduceDamage: 0,    
    basicAtk: 142,        
    basicDef: 30,        
    basicHP: 1000,         
    basicHeal: 1710,       
    skill: 0,           
    cdSkill: 0          
};
// characterAttributes['？？？']
// characterAttributes['？？？']
characterAttributes['白兽'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '爪',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 60,          
    addDef: 38,          
    addHP: 41,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 107,        
    basicDef: 28,        
    basicHP: 980,         
    basicHeal: 0,       
    skill: 2,           
    cdSkill: 0          
};
characterAttributes['帕比'] = {
    roleProperties: '水',      
    roleOccupation: '辅助',    
    weaponType: '篮子',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 48,          
    addDef: 32,          
    addHP: 47,           
    addHeal: 21,         
    reduceDamage: 0,    
    basicAtk: 102,        
    basicDef: 36,        
    basicHP: 880,         
    basicHeal: 1375,       
    skill: 14,           
    cdSkill: 0          
};
characterAttributes['瑞秋'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '步枪',      
    weapon2Type: '无',  
    crit: 11,            
    addAtk: 70,          
    addDef: 32,          
    addHP: 34,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 118,        
    basicDef: 20,        
    basicHP: 934,         
    basicHeal: 0,       
    skill: 11,           
    cdSkill: 0          
};
characterAttributes['可可∧二星'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 60,          
    addDef: 36,          
    addHP: 42,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 116,        
    basicDef: 16,        
    basicHP: 850,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0          
};
characterAttributes['可可∧三星'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '权杖',      
    weapon2Type: '无',  
    crit: 5,            
    addAtk: 64,          
    addDef: 39,          
    addHP: 45,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 125,        
    basicDef: 18,        
    basicHP: 978,         
    basicHeal: 0,       
    skill: 10,           
    cdSkill: 0          
};
characterAttributes['凯瑟琳'] = {
    roleProperties: '水',      
    roleOccupation: '射手',    
    weaponType: '弓',      
    weapon2Type: '无',  
    crit: 6,            
    addAtk: 67,          
    addDef: 33,          
    addHP: 36,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 106,        
    basicDef: 25,        
    basicHP: 930,         
    basicHeal: 0,       
    skill: 4,           
    cdSkill: 0          
};
