/*
characterAttributes['模板'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/
characterAttributes['玛丽娜'] = {
    roleProperties: '水',       
    roleOccupation: '坦克',     
    weaponType: '单手剑',      
    weapon2Type: '无',
    crit: 0,                    
    addAtk: 45,                  
    addDef: 41,                  
    addHP: 57,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 124,                
    basicDef: 76,                
    basicHP: 1080,                 
    basicHeal: 0,                
    skill: 4,                  
    cdSkill: 8       
};
characterAttributes['比安卡'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['佳岚∧弓'] = {
    roleProperties: '水',       
    roleOccupation: '射手',     
    weaponType: '弓',      
    weapon2Type: '无',
    crit: 0,                    
    addAtk: 63,                  
    addDef: 41,                  
    addHP: 42,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 153,                
    basicDef: 16,                
    basicHP: 961,                 
    basicHeal: 1512,                
    skill: 6,                  
    cdSkill: 8  
};
characterAttributes['佳岚∧篮子'] = {
    roleProperties: '水',       
    roleOccupation: '射手',     
    weaponType: '篮子',      
    weapon2Type: '无',
    crit: 0,                    
    addAtk: 63,                  
    addDef: 41,                  
    addHP: 42,                   
    addHeal: 0,                 
    reduceDamage: 0,            
    basicAtk: 153,                
    basicDef: 16,                
    basicHP: 961,                 
    basicHeal: 1512,                
    skill: 6,                  
    cdSkill: 8  
};
characterAttributes['维罗妮卡'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['柚子∧泳装'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['奥尔卡'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['哈娜'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['娅拉'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['AA72'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['安德拉斯'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['白雪'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['汐雅'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
/*
characterAttributes['白兽'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['帕比'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['瑞秋'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['可可'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
characterAttributes['凯瑟琳'] = {
    roleProperties: '水',      
    roleOccupation: '战士',    
    weaponType: '单手剑',      
    weapon2Type: '无',  
    crit: 0,            
    addAtk: 0,          
    addDef: 0,          
    addHP: 0,           
    addHeal: 0,         
    reduceDamage: 0,    
    basicAtk: 0,        
    basicDef: 0,        
    basicHP: 0,         
    basicHeal: 0,       
    skill: 0,           
    cdSkill: 0          
};
*/