/* 权杖 */

const scepterWeaponAttributes = {
    '未装备':{
        roleProperties: '虚',       /* 武器属性 */
        weaponType: '权杖',         /* 武器类型 */
        weaponCoefficient: 3,       /* 武器系数 */
        crit: 0,                    /* 自带暴击 */
        addAtk: 0,                  /* 攻击加成 */
        addDef: 0,                  /* 防御加成 */
        addHP: 0,                   /* 生命加成 */
        addHeal: 0,                 /* 回血加成 */
        basicAtk: 0,                /* 1级攻击白值 */
        basicDef: 0,                /* 1级防御白值 */
        basicHeal: 0,               /* 1级回血值白值 */
        skill: 0,                   /* 技伤 */
        cdSkill: 0,                 /* cd */
        reduceDamage: 0,            /* 伤害减免 */
    },
    '天使之音':{
        roleProperties: '虚',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 2,                 
        addAtk: 10,               
        addDef: 15,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 209,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 0,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '亚马洛克':{
        roleProperties: '暗',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 10,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 18,                
        addHeal: 0,              
        basicAtk: 194,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 16,              
        cdSkill: 16,            
        reduceDamage: 0,         
    }, 
    '解放者':{
        roleProperties: '光',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 15,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 203,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 15,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
    '弥赛亚':{
        roleProperties: '水',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 15,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 187,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 30,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
    '幻想曲':{
        roleProperties: '火',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 13,                 
        addAtk: 10,               
        addDef: 18,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 190,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 22,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '年丰时稔':{                    /* 年丰时稔（ren） */
        roleProperties: '土',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 1,                 
        addAtk: 10,               
        addDef: 22,               
        addHP: 22,                
        addHeal: 0,              
        basicAtk: 213,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '爱之深':{
        roleProperties: '虚',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 22,                
        addHeal: 0,              
        basicAtk: 204,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 18,              
        cdSkill: 18,            
        reduceDamage: 0,         
    },
    '冲破禁锢':{
        roleProperties: '水',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 2,                 
        addAtk: 10,               
        addDef: 24,               
        addHP: 22,                
        addHeal: 0,              
        basicAtk: 211,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 14,            
        reduceDamage: 0,         
    },
    '猎头者':{
        roleProperties: '水',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 10,                 
        addAtk: 10,               
        addDef: 22,               
        addHP: 12,                
        addHeal: 0,              
        basicAtk: 195,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '菲尔诺特':{
        roleProperties: '暗',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 6,                 
        addAtk: 10,               
        addDef: 24,               
        addHP: 24,                
        addHeal: 0,              
        basicAtk: 202,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 16,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '杰洛士权杖':{
        roleProperties: '暗',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 24,                
        addHeal: 0,              
        basicAtk: 204,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 25,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '漆黑法杖':{
        roleProperties: '火',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 8,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 24,                
        addHeal: 0,              
        basicAtk: 199,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 25,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '女巫之心':{
        roleProperties: '水',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 0,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 16,                
        addHeal: 0,              
        basicAtk: 211,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 25,            
        reduceDamage: 0,         
    },
    '峨眉月':{
        roleProperties: '暗',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 24,               
        addHP: 24,                
        addHeal: 0,              
        basicAtk: 202,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 10,              
        cdSkill: 10,            
        reduceDamage: 0,         
    },
    '正义':{
        roleProperties: '光',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 2,                 
        addAtk: 10,               
        addDef: 25,               
        addHP: 18,                
        addHeal: 0,              
        basicAtk: 203,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 15,              
        cdSkill: 0,            
        reduceDamage: 70,         
    },
    '赫利俄斯':{
        roleProperties: '火',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 7,                 
        addAtk: 10,               
        addDef: 10,               
        addHP: 15,                
        addHeal: 0,              
        basicAtk: 200,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 25,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
    '逆鳞':{
        roleProperties: '火',    
        weaponType: '权杖',    
        weaponCoefficient: 3,    
        crit: 3,                 
        addAtk: 10,               
        addDef: 15,               
        addHP: 15,                
        addHeal: 0,              
        basicAtk: 205,               
        basicDef: 0,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
}