/* 双手剑 */

const twoWeaponAttributes = {
    '模版':{
        roleProperties: '虚',       /* 武器属性 */
        weaponType: '单手剑',       /* 武器类型 */
        weaponCoefficient: 3,       /* 武器系数 */
        crit: 1,                    /* 自带暴击 */
        addAtk: 1,                  /* 攻击加成 */
        addDef: 1,                  /* 防御加成 */
        addHP: 1,                   /* 生命加成 */
        addHeal: 1,                 /* 回血加成 */
        basicAtk: 1,                /* 1级攻击白值 */
        basicDef: 1,                /* 1级防御白值 */
        basicHeal: 1,               /* 1级回血值白值 */
        skill: 1,                   /* 技伤 */
        cdSkill: 1,                 /* cd */
        reduceDamage: 1,            /* 伤害减免 */
    },
    '普洛米诺斯':{
        roleProperties: '火',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 11,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 24,                
        addHeal: 0,              
        basicAtk: 314,               
        basicDef: 11,               
        basicHeal: 0,               
        skill: 0,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '勇者之心':{
        roleProperties: '光',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 10,                 
        addAtk: 10,               
        addDef: 30,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 291,               
        basicDef: 18,               
        basicHeal: 0,               
        skill: 15,              
        cdSkill: 10,            
        reduceDamage: 0,         
    },
    '阿施塔特':{
        roleProperties: '水',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 329,               
        basicDef: 10,               
        basicHeal: 0,               
        skill: 15,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '猎食者':{
        roleProperties: '暗',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 8,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 310,               
        basicDef: 16,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 8,            
        reduceDamage: 0,         
    },
    '涅瑞伊得斯':{
        roleProperties: '虚',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 3,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 16,                
        addHeal: 0,              
        basicAtk: 329,               
        basicDef: 15,               
        basicHeal: 0,               
        skill: 12,              
        cdSkill: 22,            
        reduceDamage: 0,         
    },
    '海洋守护者':{
        roleProperties: '水',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 8,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 316,               
        basicDef: 15,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '原子毁灭者':{
        roleProperties: '虚',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 0,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 22,                
        addHeal: 0,              
        basicAtk: 305,               
        basicDef: 19,               
        basicHeal: 0,               
        skill: 22,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '辐光':{
        roleProperties: '光',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 6,                 
        addAtk: 10,               
        addDef: 22,               
        addHP: 22,                
        addHeal: 0,              
        basicAtk: 291,               
        basicDef: 16,               
        basicHeal: 0,               
        skill: 20,              
        cdSkill: 12,            
        reduceDamage: 0,         
    },
    '梦魇':{
        roleProperties: '土',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 8,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 0,                
        addHeal: 0,              
        basicAtk: 287,               
        basicDef: 11,               
        basicHeal: 0,               
        skill: 24,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '皇家沙铲':{
        roleProperties: '光',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 8,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 318,               
        basicDef: 11,               
        basicHeal: 0,               
        skill: 24,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '光之剑':{
        roleProperties: '光',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 22,               
        addHP: 0,                
        addHeal: 0,              
        basicAtk: 323,               
        basicDef: 17,               
        basicHeal: 0,               
        skill: 18,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '盖米诺斯':{
        roleProperties: '虚',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 10,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 20,                
        addHeal: 0,              
        basicAtk: 293,               
        basicDef: 17,               
        basicHeal: 0,               
        skill: 0,              
        cdSkill: 10,            
        reduceDamage: 0,         
    },
    '塔尔塔洛斯':{
        roleProperties: '暗',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 15,                 
        addAtk: 10,               
        addDef: 15,               
        addHP: 15,                
        addHeal: 0,              
        basicAtk: 289,               
        basicDef: 15,               
        basicHeal: 0,               
        skill: 25,              
        cdSkill: 0,            
        reduceDamage: 60,         
    },
    '法夫尼尔':{
        roleProperties: '暗',    
        weaponType: '双手剑',    
        weaponCoefficient: 2.5,    
        crit: 5,                 
        addAtk: 10,               
        addDef: 18,               
        addHP: 14,                
        addHeal: 0,              
        basicAtk: 309,               
        basicDef: 16,               
        basicHeal: 0,               
        skill: 22,              
        cdSkill: 10,            
        reduceDamage: 0,         
    }
    
}