const magicCardAttributes = {
    '未装备':{
        crit: 0,
        addAtk: 0,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
    },
    '暴击率+3%':{
        crit: 3,
        addAtk: 0,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
    },
    '攻击+7%':{
        crit: 0,
        addAtk: 7,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
    },
    '攻击+5%':{
        crit: 0,
        addAtk: 5,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
    },
    '防御+7%':{
        crit: 0,
        addAtk: 0,
        addDef: 7,
        addHP: 0,
        addHeal: 0,
        skill: 0,
    },
    '生命+6%':{
        crit: 0,
        addAtk: 0,
        addDef: 0,
        addHP: 6,
        addHeal: 0,
        skill: 0,
    },
    '恢复能力+10%':{
        crit: 0,
        addAtk: 0,
        addDef: 0,
        addHP: 0,
        addHeal: 10,
        skill: 0,
    },
    '技能伤害值+10%':{
        crit: 0,
        addAtk: 0,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 10,
    },
}