const peripheralAttributes = {
    '无周边': {
        addAtk: 0,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
      },
      '牺牲石像样品': {
        addAtk: 12,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
      },
      '侵略者航天母舰模型': {
        addAtk: 12,
        addDef: 0,
        addHP: 0,
        addHeal: 0,
        skill: 0,
      },
      '欧格玛手办': {
        addAtk: 15,
        addDef: 0,
        addHP: 15,
        addHeal: 0,
        skill: 0,
      },
      '小公主公仔': {
        addAtk: 0,
        addDef: 9,
        addHP: 6,
        addHeal: 0,
        skill: 0,
      },
      '疯狂熊猫团奖杯': {
        addAtk: 8,
        addDef: 8,
        addHP: 8,
        addHeal: 0,
        skill: 0,
      },
      '老鼠奈莉坐垫': {
        addAtk: 12,
        addDef: 9,
        addHP: 0,
        addHeal: 0,
        skill: 0,
      },
      '冰雪魔女的T恤': {
        addAtk: 12,
        addDef: 9,
        addHP: 0,
        addHeal: 0,
        skill: 0,
      },
      '笑面神坐垫': {
        addAtk: 0,
        addDef: 0,
        addHP: 12,
        addHeal: 0,
        skill: 0,
      },
      '神秘自动售货机存钱罐': {
        addAtk: 12,
        addDef: 0,
        addHP: 0,
        addHeal: 9,
        skill: 0,
      },
      '蓝色攻击周边': {
        addAtk: 20,
        addDef: 3,
        addHP: 9,
        addHeal: 0,
        skill: 0,
      },
      '梅丽尔坐垫': {
        addAtk: 12,
        addDef: 0,
        addHP: 3,
        addHeal: 0,
        skill: 35,
      }
    };
    