/* 副武器步枪 */

const rifle2Attributes = {
    '未装备':{
        crit: 0,                    /* 自带暴击 */
        addAtk: 0,                  /* 攻击加成 */
        addDef: 0,                  /* 防御加成 */
        addHP: 0,                   /* 生命加成 */
        skill: 0,                   /* 技伤 */
        cdSkill: 0,                 /* cd */
        reduceDamage: 0,            /* 伤害减免 */
    },
    '无边绝望':{
        crit: 10,                 
        addAtk: 10,               
        addDef: 15,               
        addHP: 15,                
        skill: 20,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
    '终结者':{
        crit: 5,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 18,                
        skill: 16,              
        cdSkill: 0,            
        reduceDamage: 0,         
    },
    '宇宙毁灭者':{
        crit: 3,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 20,                
        skill: 16,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '欧米伽冲锋枪':{
        crit: 6,                 
        addAtk: 10,               
        addDef: 12,               
        addHP: 24,                
        skill: 18,              
        cdSkill: 18,            
        reduceDamage: 0,         
    },
    '反抗':{
        crit: 2,                 
        addAtk: 10,               
        addDef: 16,               
        addHP: 22,                
        skill: 24,              
        cdSkill: 16,            
        reduceDamage: 0,         
    },
    '涅墨西斯':{
        crit: 0,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 18,                
        skill: 22,              
        cdSkill: 18,            
        reduceDamage: 0,         
    },
    '湛蓝鱼矛':{
        crit: 5,                 
        addAtk: 10,               
        addDef: 18,               
        addHP: 20,                
        skill: 22,              
        cdSkill: 18,            
        reduceDamage: 0,         
    },
    'R模式·方阵刹那':{
        crit: 6,                 
        addAtk: 10,               
        addDef: 12,               
        addHP: 12,                
        skill: 16,              
        cdSkill: 10,            
        reduceDamage: 0,         
    },
    '黑曼巴':{
        crit: 12,                 
        addAtk: 10,               
        addDef: 18,               
        addHP: 20,                
        skill: 20,              
        cdSkill: 0,            
        reduceDamage: 0,         
    },
    '蜜獾手枪':{                        /* 蜜獾（huan）手枪 */
        crit: 10,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 18,                
        skill: 18,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
    '维涅特（专）':{
        crit: 3,                 
        addAtk: 10,               
        addDef: 18,               
        addHP: 18,                                      
        skill: 22,              
        cdSkill: 0,            
        reduceDamage: 0,         
    },
    '捣蛋鬼':{
        crit: 2,                 
        addAtk: 10,               
        addDef: 15,               
        addHP: 18,                
        skill: 20,              
        cdSkill: 18,            
        reduceDamage: 0,         
    },
    '无情':{
        crit: 6,                 
        addAtk: 10,               
        addDef: 20,               
        addHP: 18,                
        skill: 0,              
        cdSkill: 16,            
        reduceDamage: 35,         
    },
    '蓝玫瑰':{
        crit: 10,                 
        addAtk: 10,               
        addDef: 18,               
        addHP: 20,                
        skill: 20,              
        cdSkill: 15,            
        reduceDamage: 0,         
    },
    '神奇激光风暴':{
        crit: 5,                 
        addAtk: 10,               
        addDef: 0,               
        addHP: 16,                
        skill: 20,              
        cdSkill: 20,            
        reduceDamage: 0,         
    },
    '协商者':{
        crit: 30,                 
        addAtk: 0,               
        addDef: 8,               
        addHP: 10,                                 
        skill: 24,              
        cdSkill: 18,            
        reduceDamage: 0,         
    },
}